export const COLORS = {
  primary:           "#007aff",
  primarylight:      "#cfe5ff",
  primarylightHover: "#b8d8ff",
  secondary:         "#5856d6",
  purpleLight:       "#dadafa",
  success:           "#34c759",
  warning:           "#ff9500",
  error:             "#ff3b30",
  info:              "#32ade6",
  backgroundDefault: "#f5f5f7",
  black:             "#000000",
  text:              "#222224",
  subText:           "#3C3C4380",
  neutral:           "#8e8e93",
  backgroundPaper:   "#fbfbfd",
  graylight:         "#3c3c431f",
  pillBg:            "#f2f2f7",
  pillSelected:      "#007aff",
  white:             "#ffffff",
  border:            "#3c3c432e",
  primaryHover:      "#0066d9",
  grayMedium:        "#9e9e9e",
  purple:            "#af52de",
  teal:              "#30b0c7",
  redLight:          "#ff6961",
  textLabelBlack:  "#1c1c1e",
  disabledBorder:  "#d1d1d6",
  // status badge backgrounds
  grayLighter:     "#f5f5f5",
  purpleLighter:   "#f3e5f5",
  greenLight:      "#e8f5e9",
  tealLight:       "#e0f2f1",
  pinkLight:       "#fce4ec",
  orangeLight:     "#fff3e0",
  blueLight:       "#e3f2fd",
  indigoLight:     "#e8eaf6",
  redLighter:      "#ffebee",
  // status badge text colors
  grayDark:        "#757575",
  disabledBg: "#e0e0e0",
  disabledText: "#9e9e9e;",
  blueDark:        "#0052cc",
  indigoDark:      "#3730a3",
  purpleDark:      "#6a1b9a",
  greenDark:       "#2e7d32",
  tealDark:        "#004d40",
  redDark:         "#c62828",
  orangeDark:      "#e65100",
  blueDeep:        "#1565c0",
  indigoDeep:      "#283593",
  redDeep:         "#b71c1c",
} as const

export const PO_STATUS_BAR_COLORS: Record<string, string> = {
  draft:            COLORS.grayMedium,
  issued:           COLORS.primary,
  acknowledged:     COLORS.secondary,
  partial_received: COLORS.purple,
  received:         COLORS.success,
  closed:           COLORS.teal,
  cancelled:        COLORS.error,
  // Phase 2 — approval flow (not yet implemented)
  // pending_approval: COLORS.warning,
  // approved:         COLORS.primary,
  // sent_to_supplier: COLORS.secondary,
  // rejected:         COLORS.redLight,
} as const

export const PO_STATUS_COLORS = {
  draft:            { bg: COLORS.grayLighter,   color: COLORS.grayDark   },
  issued:           { bg: COLORS.primarylight,  color: COLORS.blueDark   },
  acknowledged:     { bg: COLORS.purpleLight,   color: COLORS.indigoDark },
  partial_received: { bg: COLORS.purpleLighter, color: COLORS.purpleDark },
  received:         { bg: COLORS.greenLight,    color: COLORS.greenDark  },
  closed:           { bg: COLORS.tealLight,     color: COLORS.tealDark   },
  cancelled:        { bg: COLORS.pinkLight,     color: COLORS.redDark    },
  // Phase 2 — approval flow (not yet implemented)
  // pending_approval: { bg: COLORS.orangeLight,   color: COLORS.orangeDark },
  // approved:         { bg: COLORS.blueLight,     color: COLORS.blueDeep   },
  // sent_to_supplier: { bg: COLORS.indigoLight,   color: COLORS.indigoDeep },
  // rejected:         { bg: COLORS.redLighter,    color: COLORS.redDeep    },
} as const
