export const ROUTES = {
  login: "/login",
  home: "/",
  customers: "/customers",
  suppliers: "/suppliers",
  products: "/products",
  quotations: "/quotations",
  purchaseOrders: "/purchase-orders",
  receiving: "/receiving",
  upload: "/upload",
  chat: "/chat",
  email: "/email",
  quote: "/quote",
  mailbox: "/mailbox",
  import: "/import",
  report: "/report",
  notification: "/notification",
  users: "/users",
  roles: "/roles",
  setting: "/setting",
} as const
